name: "南京大学软件学院十周年庆"
description: "南京大学软件学院成立十周年。2002-2012"
keywords: [南京大学, 软件学院, 十周年, 院庆]
baseurl: /

permalink: none
markdown: rdiscount
pygments: false
lsi: false

include:
 - .htaccess

exclude:
 - README.md
 - Rakefile
 - jquery.googlemaps1.01.js
 - jquery.masonry.min.js
 - jquery.R-Forms.js
 - jquery.tipsy.js
 - RSlider.js
 - PTSansNarrow_400.js
 - msyh.font.js
 - logo.psd
 - view-projects-btn.psd
