name: "南京大学软件学院成立十周年"

markdown: rdiscount
pygments: false
lsi: false

include:
 - .htaccess

exclude:
 - README.md
 - jquery.googlemaps1.01.js
 - jquery.masonry.min.js
 - jquery.R-Forms.js
 - jquery.tipsy.js
 - RSlider.js
 - PTSansNarrow_400.js
